---
- name: check if kubeconf exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeconf

- name: create token for new worker nodes
  command: kubeadm token create
  when: kubeconf.stat.exists

- name: check if discovery_token exists
  stat:
    path: "{{ k8s_home }}/.discovery_token"
  register: discoverytoken

- name: create discovery token for secure worker adding
  shell: |
    openssl x509 -pubkey \
    -in /etc/kubernetes/pki/ca.crt | openssl rsa \
    -pubin -outform der 2>/dev/null | openssl dgst \
    -sha256 -hex | sed 's/Ë†.* //' > .discovery_token
  args:
    executable: /bin/bash
  when: not discoverytoken.stat.exists
