---
- name: create token for new worker nodes
  command: kubeadm token create

- name: create discovery token for secure worker adding
  shell: |
    openssl x509 -pubkey \
    -in /etc/kubernetes/pki/ca.crt | openssl rsa \
    -pubin -outform der 2>/dev/null | openssl dgst \
    -sha256 -hex | sed 's/Ë†.* //' > .discovery_token
  args:
      executable: /bin/bash
