---
- name: install k8s components in version {{ k8s_version }}
  apt:
    name: "{{ k8s_components }}"
    state: present

- name: disable auto update of k8s components
  command: apt-mark hold kubelet kubeadm kubectl

- name: initialize k8smaster
  shell: |
    kubeadm init --kubernetes-version=1.18.1 \
    --node-name=k8smaster \
    --apiserver-advertise-address=192.168.56.160 \
    --control-plane-endpoint=k8smaster:6443 \
    --pod-network-cidr=192.168.0.0/16 \
    --upload-certs \
    | tee kubeadm-init.out
  args:
    executable: /bin/bash
