---
- name: install k8s components in version {{ k8s_version }}
  apt:
    name: "{{ k8s_components }}"
    state: present

- name: disable auto update of k8s components
  command: apt-mark hold kubelet kubeadm kubectl

- name: check if kubeadm-init exists
  stat:
    path: "{{ k8s_home }}/kubeadm-init.out"
  register: kubeadminit


- name: initialize k8smaster
  shell: |
    kubeadm init --kubernetes-version={{ k8s_version }} \
    --node-name={{ k8s_hostname }} \
    --apiserver-advertise-address={{ k8s_master_ip }} \
    --control-plane-endpoint={{ k8s_hostname }}:{{ k8s_master_port }} \
    --pod-network-cidr={{ pod_subnet }} \
    --upload-certs \
    | tee kubeadm-init.out
  args:
    executable: /bin/bash
  when: not kubeadminit.stat.exists
