---
- name: kube directory for kubectl config file
  file:
    path: "{{ k8s_home }}/.kube"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    state: directory

- name: check if kubeconf exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeconf

- name: Copy kubeconf file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ k8s_home }}/.kube/config"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    remote_src: yes
  when: kubeconf.stat.exists
